/**
 * memoryEngine.js
 *
 * PERSISTENT CONTEXT MEMORY ENGINE
 *
 * Maintains conversation state across turns within a session and
 * provides a serialisable snapshot for cross-session persistence.
 *
 * Memory layers:
 *   1. WORKING MEMORY  — current turn's active context (cleared each turn)
 *   2. SESSION MEMORY  — persists within one agent session (product refs,
 *                        last discussed topic, recent queries)
 *   3. LONG-TERM MEMORY— serialisable to JSON for cross-session persistence
 *                        (product nicknames, user preferences, repair history
 *                        confirmations, repeated issues)
 *
 * Coreference resolution:
 *   The memory engine maintains a "focus stack" — a prioritised list of
 *   products/topics mentioned in the conversation. When a query contains
 *   pronouns ("it", "that product") or bare issue descriptions with no
 *   product reference, the focus stack supplies the missing context.
 *
 * Usage:
 *   const mem = new MemoryEngine();
 *   mem.recordTurn(nluFrame, agentResponse);
 *   const context = mem.getContext();  // pass to agent on next turn
 */

export class MemoryEngine {
  constructor(initialState = null) {
    // Focus stack: [{productId, productName, brand, category, lastMentionedAt}]
    this._focusStack = [];

    // Recent turn history: [{turn, query, intent, productsInvolved, answeredAt}]
    this._history = [];

    // Long-term facts: confirmed facts about products and the user
    this._longTermFacts = new Map(); // key → { value, confirmedAt, source }

    // Pending follow-ups the agent suggested
    this._pendingFollowUps = [];

    // Active alerts generated by autonomous monitoring
    this._activeAlerts = [];

    // Session metadata
    this._sessionStarted = new Date().toISOString();
    this._turnCount = 0;

    // Restore from serialised state if provided
    if (initialState) this._restore(initialState);
  }

  // ── TURN RECORDING ──────────────────────────────────────────────────────────

  /**
   * Records a completed turn (NLU frame + agent response) into memory.
   * Called by the agent orchestrator after every turn.
   */
  recordTurn(nluFrame, agentResponse) {
    this._turnCount++;

    const turn = {
      turnNumber: this._turnCount,
      query: nluFrame.raw,
      intent: nluFrame.intent,
      urgencyLevel: nluFrame.urgencyLevel,
      entities: {
        brands: nluFrame.entities.brands.map((b) => b.brand),
        categories: nluFrame.entities.categories,
        issueTypes: nluFrame.entities.issueTypes.map((i) => i.issueType),
      },
      productsInvolved: (agentResponse.products || []).map((p) => ({
        id: p.id,
        name: p.productName,
        brand: p.brand,
        category: p.category,
      })),
      answeredAt: new Date().toISOString(),
    };

    this._history.push(turn);
    // Keep last 20 turns in session memory
    if (this._history.length > 20) this._history.shift();

    // Update focus stack with products from this turn
    for (const product of agentResponse.products || []) {
      this._updateFocusStack(product);
    }

    // Extract and store long-term facts from this turn
    this._extractFacts(nluFrame, agentResponse);

    // Clear consumed follow-up suggestions
    this._pendingFollowUps = agentResponse.followUpSuggestions || [];
  }

  _updateFocusStack(product) {
    if (!product?.id) return;
    // Remove if already in stack (will re-add at top)
    this._focusStack = this._focusStack.filter((f) => f.productId !== product.id);
    // Push to top of focus stack
    this._focusStack.unshift({
      productId: product.id,
      productName: product.productName,
      brand: product.brand,
      category: product.category,
      lastMentionedAt: new Date().toISOString(),
    });
    // Keep focus stack bounded
    if (this._focusStack.length > 5) this._focusStack = this._focusStack.slice(0, 5);
  }

  _extractFacts(nluFrame, agentResponse) {
    // If the agent confirmed a warranty is active for a product, store that
    for (const product of agentResponse.products || []) {
      if (product.warrantyTimeline) {
        this._longTermFacts.set(`warranty_status_${product.id}`, {
          value: product.warrantyTimeline.isActive ? 'active' : 'expired',
          expiryDate: product.warrantyTimeline.expiryDate,
          confirmedAt: new Date().toISOString(),
          source: 'agent_reasoning',
        });
      }

      // Track reported issues per product
      if (nluFrame.entities.issueTypes.length > 0) {
        const issueKey = `reported_issue_${product.id}`;
        const existing = this._longTermFacts.get(issueKey) || { issues: [] };
        const newIssues = nluFrame.entities.issueTypes.map((i) => ({
          issueType: i.issueType,
          reportedAt: new Date().toISOString(),
          query: nluFrame.raw,
        }));
        existing.issues = [...(existing.issues || []), ...newIssues].slice(-10);
        this._longTermFacts.set(issueKey, existing);
      }
    }
  }

  // ── CONTEXT RETRIEVAL ───────────────────────────────────────────────────────

  /**
   * Returns the full context object passed to the agent on each turn.
   * This is what the NLU engine, reasoning engine, and orchestrator use.
   */
  getContext() {
    const primary = this._focusStack[0] || null;

    return {
      // Current focused product (coreference target)
      currentProductId: primary?.productId || null,
      currentProductName: primary?.productName || null,
      currentBrand: primary?.brand || null,
      currentCategory: primary?.category || null,

      // Full focus stack (for multi-product coreference)
      focusStack: this._focusStack.slice(),

      // For entity extractor coreference resolution
      lastBrands: this._focusStack.slice(0, 3).map((f) => ({ brand: f.brand, confidence: 0.9, method: 'context-memory' })).filter((f) => f.brand),
      lastCategories: this._focusStack.slice(0, 3).map((f) => f.category).filter(Boolean),

      // Recent conversation history (last 5 turns)
      recentHistory: this._history.slice(-5),

      // Long-term facts for augmenting reasoning
      longTermFacts: Object.fromEntries(this._longTermFacts),

      // Pending follow-ups the agent offered last turn
      pendingFollowUps: this._pendingFollowUps.slice(),

      // Active alerts from autonomous monitoring
      activeAlerts: this._activeAlerts.slice(),

      // Session stats
      turnCount: this._turnCount,
      sessionStarted: this._sessionStarted,
    };
  }

  /**
   * Returns previously confirmed issue reports for a product (used by the
   * failure prediction engine and multi-turn reasoning to understand history).
   */
  getReportedIssues(productId) {
    return (this._longTermFacts.get(`reported_issue_${productId}`) || { issues: [] }).issues;
  }

  /**
   * Returns the last N queries with their intents (for context analysis).
   */
  getRecentQueries(n = 5) {
    return this._history.slice(-n).map((t) => ({ query: t.query, intent: t.intent }));
  }

  // ── ALERT MANAGEMENT ────────────────────────────────────────────────────────

  addAlert(alert) {
    const existing = this._activeAlerts.find((a) => a.id === alert.id);
    if (!existing) {
      this._activeAlerts.push({
        ...alert,
        createdAt: new Date().toISOString(),
        shown: false,
      });
    }
  }

  markAlertShown(alertId) {
    const alert = this._activeAlerts.find((a) => a.id === alertId);
    if (alert) alert.shown = true;
  }

  getUnshownAlerts() {
    return this._activeAlerts.filter((a) => !a.shown);
  }

  clearExpiredAlerts(referenceDate = new Date()) {
    this._activeAlerts = this._activeAlerts.filter((a) => {
      if (!a.expiresAt) return true;
      return new Date(a.expiresAt) > referenceDate;
    });
  }

  // ── SERIALISATION ───────────────────────────────────────────────────────────

  /**
   * Serialises memory state to a plain JSON-safe object for storage.
   * Call this to persist state between sessions (localStorage, DB, file).
   */
  serialize() {
    return {
      focusStack: this._focusStack,
      history: this._history.slice(-10), // persist last 10 turns only
      longTermFacts: [...this._longTermFacts.entries()],
      activeAlerts: this._activeAlerts,
      sessionStarted: this._sessionStarted,
      turnCount: this._turnCount,
      serializedAt: new Date().toISOString(),
    };
  }

  _restore(state) {
    if (!state) return;
    this._focusStack = state.focusStack || [];
    this._history = state.history || [];
    this._longTermFacts = new Map(state.longTermFacts || []);
    this._activeAlerts = state.activeAlerts || [];
    this._sessionStarted = state.sessionStarted || this._sessionStarted;
    this._turnCount = state.turnCount || 0;
  }

  static fromSerialized(state) {
    return new MemoryEngine(state);
  }
}

export default MemoryEngine;
